apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: myapp
    repoURL: https://github.com/Krreesh/argoapp.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
